// <auto-generated />
using System;
using AdminUsers.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AdminUsers.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20230907175220_primeramigracion")]
    partial class primeramigracion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AdminUsers.Models.Cargo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("bit");

                    b.Property<string>("codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idUsuarioCreacion")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("cargos");
                });

            modelBuilder.Entity("AdminUsers.Models.Departamento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("bit");

                    b.Property<string>("codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idUsuarioCreacion")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("departamentos");
                });

            modelBuilder.Entity("AdminUsers.Models.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("idCargoid")
                        .HasColumnType("int");

                    b.Property<int?>("idDepartamentoid")
                        .HasColumnType("int");

                    b.Property<string>("primerApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("primerNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("segundoApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("segundoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usuario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("idCargoid");

                    b.HasIndex("idDepartamentoid");

                    b.ToTable("users");
                });

            modelBuilder.Entity("AdminUsers.Models.Usuario", b =>
                {
                    b.HasOne("AdminUsers.Models.Cargo", "idCargo")
                        .WithMany()
                        .HasForeignKey("idCargoid");

                    b.HasOne("AdminUsers.Models.Departamento", "idDepartamento")
                        .WithMany()
                        .HasForeignKey("idDepartamentoid");

                    b.Navigation("idCargo");

                    b.Navigation("idDepartamento");
                });
#pragma warning restore 612, 618
        }
    }
}
